  runtime: nodejs
  env: flex

  runtime_config:
      operating_system: "ubuntu22"
      runtime_version: "20"

  resources:
    memory_gb: 4  # Adjust based on your needs
    cpu: 2
    disk_size_gb: 10

  env_variables:
    ALLOWED_ORIGINS: "*"
    GOOGLE_CLOUD_STORAGE_BUCKET: "real-9f3b8.appspot.com"

  automatic_scaling:
    cpu_utilization:
      target_utilization: 0.6

  network:
    session_affinity: true

  handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
